### ISSUE TITLE
Update Console topic UI to indicate that retention.bytes is per-partition, not per topic

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/console#1010]
We seem to get questions on a frequent enough basis about the disparity between retention.bytes as configured and the total size of a topic as viewed in Console. Can we get the UI annotated to indicate that retention.bytes is the per-partition retention and not the overall topic bytes retention?

I know I've fielded this a few times for customers, and Josh Purcell had one today.

[Slack Message](https://redpandadata.slack.com/archives/C02RQPX6A1K/p1705525631276369?thread_ts=1705525631.276369&cid=C02RQPX6A1K)

**Comment by hcoyote** [comment]
![image](https://github.com/redpanda-data/console/assets/751025/4e294f01-79a6-4188-89f9-4af9e968dd75)

Red arrow is where I'm talking about. The disparity between the 10GB retention.bytes value that applies to the individual partition and the 134GB actual topic content size is what causes confusion.

**Comment by weeco** [comment]
Under the configurations tab each config is explained (there's a help tooltip for each config that explains it in more detail). There are more catches with retention enforcement such as knowing about active/inactive segments etc. So not sure what we need to do more than this, but I'll leave it to @mo-redpanda & @ivpanda

**Comment by weeco** [comment]
> Show the actual retention.bytes (e.g. if there are 3 partitions, show 30GB)?

This is not a good idea, since the majority probably knows that all such configs (segment.bytes, retention.bytes etc) are applied per partition and not per topic this would confuse the majority that understood and did not complain about this setting.

> Add a tooltip indicating this is per partition

Personally I'm not a fan of tooltips if it's possibly to avoid them. So wondering if we can just fix it by showing a per partition hint. I suggested the following as part of the message viewer improvements, what do you think?

![ss-vsHRaVLn@2x](https://github.com/redpanda-data/console/assets/23424570/df76e123-4d0e-48b2-b6d7-dc7e293265cb)

**Comment by weeco** [comment]
@jvorcak This was already done, see this screenshot from latest master. I'll close this issue:

![ss-cfaDOEMc@2x](https://github.com/user-attachments/assets/2c4e58bf-d71d-4786-9d82-ea6651e02f3b)
