### ISSUE TITLE
Message content is too large and has been omitted

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#1053]
Hi,

version 2.4.0

Is there any property to increase the value for the content size so that it is shown?

Because 2KB is a bit too little.

![image](https://github.com/redpanda-data/console/assets/95491982/c8691b39-8dc7-4633-8176-df6572680eab)

**Comment by weeco** [comment]
Yes you can use: `console.maxDeserializationPayloadSize` to specify the limit in bytes. It defaults to 20KiB currently. We will probably add a button to lazy load these messages on demand if they exceed this size. Messages above a certain size can crash the frontend (due to limited resources) when we try to render the JSON in the DOM, this is why we introduced the limit

**Comment by ErykCh** [comment]
This would be the best solution if there was a lazy load option when it exceeds this size.
