### ISSUE TITLE
Add an indicator that message count is an estimate on the main topic page

### ISSUE THREAD

**Issue by patrickangeles** [redpanda-data/console#1064]
We already show that message count is an estimate in the Partitions tab. Would be good to add this to the main page as well. A tooltip when hovering the number (something non-intrusive) could work fine.

![image](https://github.com/redpanda-data/console/assets/135980/bc318b83-a82e-4bce-85ed-ddad7689110b)

**Comment by jvorcak** [comment]
![Screenshot 2024-06-11 at 17 53 38](https://github.com/redpanda-data/console/assets/1083817/7923d599-6497-4392-a7d5-2baf29c80391)

Something like this could work?

**Comment by weeco** [comment]
@jvorcak We should just change the label description from "Messages" to "Estimated Messages" - regardless of the cleanup policy. Even for cleanup.policy = delete it may be an estimate only because the cleanup policy may have been compact or because of control records which are not actual messages but would still be counted as messages. 

I assume the tooltip could be used to explain why it's an estimate only though! Maybe something along those lines:

> The number of messages shown is an estimate. This is calculated by summing the differences between the highest and lowest offsets in each partition. The actual number of messages may vary due to factors such as message deletions, log compaction, and uncommitted or transactional messages.
