### ISSUE TITLE
Topic configs - Info tooltip UI regression

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1087]
Today:

- Sizing of the fonts looks weird
- Styling of that tooltip feels misaligned

![ss-wl2wJJNN](https://github.com/redpanda-data/console/assets/23424570/6db2f615-9656-4356-b036-0c21c42c7b53)

**Comment by ivpanda** [comment]
## Design proposal: 

We can actually remove all of this information that's in the popover to begin with that makes it crowded. The outcome is what's important to the user, as well as the source. We can make that less obscure by doing the following: 

### Infinite 

<img width="381" alt="image" src="https://github.com/redpanda-data/console/assets/129790723/df1dd78a-6f39-48a5-b26b-4b766eae16f5">

### Numeric value

<img width="377" alt="image" src="https://github.com/redpanda-data/console/assets/129790723/6dc4338e-74c1-4587-bda5-4dda31e273c0">

These would use the `heading-s` text formatting for the title, and `text-s` for the copy.

**Comment by jvorcak** [comment]
@ivpanda I like the way you present it, but this would require rephrasing the texts and changing the API, because the texts come from there. I've made the quick fix that looks, I think, better than what we have now. https://github.com/redpanda-data/console/pull/1498

If you still want to implement this design, feel free to re-open.
