### ISSUE TITLE
Datepicker yields wrong times

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1096]
When using the feature to edit consumer group offsets by time using an UTC timestamps it seems the datepicker converts timestamps wrong (AM / PM is mixed and should be the opposite).

**Comment by jvorcak** [comment]
I'd need a bit more info on how to reproduce this. As far as I've checked today, it should behave as expected. https://www.loom.com/share/45ebddc75922478bbdfa79d4091b5e9b

**Comment by wzzzrd86** [comment]
Here is what the customer provided to me, if that doesn't help I can try to pull a video.

- If you try to type any values into the time field shown in the consumer group edit dialog instead of using the “pickers” the webpage breaks and goes white
 
- Using it now and the picker just outright doesn’t do what it is supposed to. PM sets the time to AM and vice versa. And trying to pick a UTC time just doesn’t select the correct time.
