### ISSUE TITLE
Unable to use api /api/topics/{topic}/messages 

### ISSUE THREAD

**Issue by polebug** [redpanda-data/console#1229]
We upgraded the Redpand version and found that this api is not accessible. 

After requesting the `/api/topics/{topic}/messages` , the response is:
```
{
 "statusCode": 404,
 "message": "Resource was not found."
}
```

Is there a new API to replace the old one?

If there is no new API, what version should I switch to so I can use this old one?

I really need some help 😭

@rikimaru0345

**Comment by bojand** [comment]
Hello, the endpoint in question was used by the Console frontend to perform querying and listing of messages in the topic view. It utilized websockets; and proved to be cumbersome to use and implement, and problematic under certain deployment scenarios. 

We have since switched the "list messages" endpoint to a gRPC / Connect RPC call that just uses standard HTTP2 and solves some of the issues with the previous implementation. So the old endpoint does not exist any more in newer versions of Console.

Note that these routes are not really a part of any kind of stable API for external consumption. They are explicitly designed and implemented to be used by Console frontend exclusively.
