### ISSUE TITLE
Show XML as XML.....

### ISSUE THREAD

**Issue by steve-gray** [redpanda-data/console#1259]
*EDIT* one of my team found a way to get this data out in raw format, but it feels like it's super hard to work with generally.

When working with topics that contain XML data, the exported data is JSON-ified and even when exporting it is in that format. It'd be handy to have:

- XML shown as XML....
- Copy to clipboard should be in XML format....
- Export should contain the data in an XML format (even if its an XML string buried inside a JSON wrapper with the message headers/key info).

Otherwise it's strangely painful to work with. Maybe we're missing a trick here?

![image](https://github.com/redpanda-data/console/assets/14563775/eb9a6913-d773-4ff9-9a2a-4de000023388)

**Comment by weeco** [comment]
Hey,
we render all structured data in a JSON viewer, regardless whether this is Protobuf, JSON, XML, Avro, Smile or any other format. We probably won't change this as we would have to support too many different formats otherwise. One thing you could try is to change the deserialization format (introduced in a v2.4.x version) from "Auto" to "String" though. Does that work?

Copying to clipboard in XML format and especially downloading/exporting in the original format makes sense to me.

**Comment by weeco** [comment]
Should already be possible by configuring the Deserializer strategy to "Text"
