### ISSUE TITLE
Viewing Avro messages crashes Redpanda Console

### ISSUE THREAD

**Issue by philipp94831** [redpanda-data/console#1326]
Ever since upgrading from v2.4.6 to v2.4.7, Redpanda Console crashes when viewing some Avro messages. Most recent version v2.6.1 also has this issue. In v2.4.7 the Avro dependency was bumped: [`v2.4.6..v2.4.7`#diff-10e03f00c5](https://github.com/redpanda-data/console/compare/v2.4.6..v2.4.7#diff-10e03f00c5bf8508d67e327c7a19879247498e8392ec699e9a05afcd36a8ed1fR29). Since there have been [new releases of the library ](https://github.com/hamba/avro/releases), I assume that updating it solves the issue.

This is the error log: [redpanda_console.log](https://github.com/user-attachments/files/16172839/redpanda_console.log)

**Comment by weeco** [comment]
Thanks for investigating and the clear report. WIll file a PR shortly

**Comment by mdjokic** [comment]
@weeco Just want to report that this issue is still happening with v2.7.0 Redpanda Console. I think that hamba/avro should be at least v2.23.0 to have same behavior as Redpanda Console v2.4.6 (because this version supported recursive avro schemas)
v2.7.0 error log: [redpanda_console.log](https://github.com/user-attachments/files/16512786/redpanda_console.log)

**Comment by weeco** [comment]
@mdjokic THanks for reporting, I'm unsure what happened but I believe a PR merge reset the version to the older version. We'll cut a patch release soon and I'll make sure to upgrade the avro library to v2.24.0
