### ISSUE TITLE
Add basic auth to be able to password protect Redpanda Console

### ISSUE THREAD

**Issue by BrianTAllen** [redpanda-data/console#1515]
Currently it looks like the only way to secure Redpanda Console is with RBAC or other features which require a license.

This request is to add support for basic auth so Redpanda Console can be password-protected even without a license.

**Comment by weeco** [comment]
Hey, in fact this already exists - mostly for demo purposes since it's hard to secure this for production environments. See here: https://docs.redpanda.com/current/console/config/security/plain/

Authentication is an enterprise feature, that includes the basic auth / plain login. You can obviously put any sort authentication in front of Console (e.g. a reverse proxy that does enforce basic auth).

**Comment by BrianTAllen** [comment]
It exists, but as the page says "this feature requires an Enterprise license" (due to the fact that it requires RBAC, which is enterprise-only.

When you add the `login` and `plain` YAML as shown (but without the RBAC) the logs show a message about not working until Redpanda Console supports plain auth without RBAC (which is what I'm requesting / encouraging / giving visibility to with this ticket).

> failed to validate enterprise config: failed to validate RBAC config: RBAC must be enabled **until a RBAC-less mode is supported in Redpanda Console**

If non-RBAC basic auth isn't on the roadmap for Console (is never going to happen) then maybe that text should be removed from the log output to avoid confusion. Thanks
