### ISSUE TITLE
Edit Topic Configs

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#260]
Add the possibility to edit topic configs via the UI.

**Comment by brycefisher** [comment]
If I wanted to open a PR to add this functionality, could someone give me some pointers?

**Comment by weeco** [comment]
Hey @brycefisher ,
this specific feature has already been merged into master. Feel free to test this!

Apparently we had two issues for this feature, and I closed the other issue only :-).

**Comment by brycefisher** [comment]
Indeed you have!! I was initially confused because this feature is not currently released in the main docker repository, but it is released as the docker image/tag [lvectorized/console-unstable:master-16ba04e](https://hub.docker.com/layers/vectorized/console-unstable/master-16ba04e/images/sha256-35acfb4dc37c7c3c4b3380f023725b6cff148e9e4154a75fd9f45d66e7655fdb?context=explore) and is very slick. Thank you so much, @weeco !
