### ISSUE TITLE
Feature: Make filters bookmarkable

### ISSUE THREAD

**Issue by rd-malte-mauelshagen** [redpanda-data/console#304]
A common use-case for us is to search for messages on a topic with:
- a given filter
- a specific 'Start Offset' (usually a timestamp from one week ago)

It would be great if those settings could be shared with other people via a deep link or bookmark. This would make it much easier to communicate about certain messages than having to copy the individual values or having to describe which filter and start offset were used to reproduce the message.

I am not sure if it's feasible to encode the whole JS filter-snippet within the URL parameter or persisting the filter and and referencing it via an ID? Anyway, that would be a great feature!

**Comment by weeco** [comment]
Absolutely agree with you. We haven't put them in an encoded form in the URL parameters because the length is unbounded. That's also where the complexity comes in because I think that this should be stored and served in the backend, which again requires a persistence (some db) which we do not have yet.

This is one of the reasons why we plan on adding a database so that we can add more features like this, thanks for filing the issue :-).

**Comment by twmb** [comment]
Filters are cached frontend, we just closed another issue related to sharing filters -- if we see this enough we may try to create a dedicated way-to-share-filters feature request. Until then, closing.
