### ISSUE TITLE
How do I get topic details back after I turn off some attribute display

### ISSUE THREAD

**Issue by cobolbaby** [redpanda-data/console#316]
![2022-02-17 10-41-51屏幕截图](https://user-images.githubusercontent.com/11460848/154394438-84b33518-0aa7-4127-9a35-5221bc344f8e.png)

How do I get it back after I turn off some attribute display? I didn't find `Quick Info`.

In addition, I would like to ask how long the cache of topic details information is valid. After I modify segment.ms, the value of this attribute remains the same for a long time.

version: v1.5.0, 1.4.0

**Comment by cobolbaby** [comment]
```
root@broker1:/# kafka-configs kafka-configs --bootstrap-server localhost:19092 --describe --entity-type topics --entity-name f6-ict-3070-result-log
Dynamic configs for topic f6-ict-3070-result-log are:
  retention.ms=2592000000 sensitive=false synonyms={DYNAMIC_TOPIC_CONFIG:retention.ms=2592000000}
```

**Comment by rikimaru0345** [comment]
Hi, 

> How do I get it back after I turn off some attribute display?

previously you were able you were able to click on the name of a config-entry (in the config tab of a topic), that's where you would select what is shown in the statistics bar at the top.

However, due to a recent refactoring that got lost, sorry about that.

At least right now the only way to fix it is to reset the settings 😦 

![image](https://user-images.githubusercontent.com/28133019/155880559-833ef74c-23b5-4438-a9d1-6d38a8f14302.png)


> After I modify segment.ms, the value of this attribute remains the same for a long time.

The frontend caches information for 20seconds. But that only gets triggered when you navigate around the page.
So if you view a topic, then go to the brokers page, then back to topics, and click your topic again, it will reload the info.

Otherwise you can refresh the info manually by clicking on the blue reload button at the top.
Does it update if you click that?
If not, please show the network response so we can check if it is a frontend or backend issue.


![image](https://user-images.githubusercontent.com/28133019/155880635-661a8fc7-4ee2-45e0-85bb-4237535a7122.png)

**Comment by cobolbaby** [comment]
> At least right now the only way to fix it is to reset the settings

Got it.

> After I modify segment.ms, the value of this attribute remains the same for a long time.

Sorry, there is nothing wrong with the service, I mistaken `segment.ms` for `retention.ms`.

**Comment by twmb** [comment]
Closed, this functionality has been removed
