### ISSUE TITLE
Feature request: Support publishing byte array messages

### ISSUE THREAD

**Issue by omeraha** [redpanda-data/console#371]
Support publishing pure byte array messages

**Comment by rikimaru0345** [comment]
Maybe the UI is a bit unclear here.
When you select the option in the screenshot, the UI expects you to pass in the binary data as base64 (because copy-pasting binary data in a text-field won't really work). 

When the request reaches the backend, it will "unpack" / decode the base64 and send the actual raw bytes as the message 😄 

So you *really are* sending "pure" byte arrays.
