### ISSUE TITLE
[BUG] Icons are doubled by .anticon-icon:before

### ISSUE THREAD

**Issue by meysampg** [redpanda-data/console#385]
I've run `console:master-217260f` and similar to kowl (and of course other fronts based on anticon) icons are mirrored in firefox.

OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

Browser:
![Screenshot from 2022-06-15 15-21-39](https://user-images.githubusercontent.com/1416085/173810374-48150366-4d08-4b3f-8818-959e94446fa8.png)

Sample Problem:
![Screenshot 2022-06-15 at 15-18-22 Brokers - Redpanda Console](https://user-images.githubusercontent.com/1416085/173810434-f391761d-6258-403f-b11c-05182a70ae97.png)

Related Issue:
 - https://github.com/ant-design/ant-design/issues/12258 (and probably related solution on its last answer)

**Comment by rikimaru0345** [comment]
Interesting! 
Unfortunately, I can't reproduce the problem. (same firefox version)

It looks like only the last two icons are affected, even though all 4 links are using pretty much the exact same setup in the code.

Just in case, because I can see this might make a difference here: does clearing the browser cache have any effect on this?

And if possible, could you check whether or not there is an actual second copy of the icon present in the DOM?
If so, do they have the same exact styles? or are there any differences?

**Comment by meysampg** [comment]
I apologize, based on your comment I ran firefox in troubleshoot mode and the problem disappeared. So I disabled all my extensions and enabled them one by one. The root of the problem was caused by one of my extensions. 

Thanks for your note. It solved my problem :heart:.
