### ISSUE TITLE
How to change size of max results, currently max is 500 (frontend)

### ISSUE THREAD

**Issue by nitin1677** [redpanda-data/console#416]
when we try to search events in kafka topic based on timestamp or offset, max we can see up to 500 events.

If kafka topics has larger no of events based on search pattern, how to navigate events if larger than 500.

**Comment by weeco** [comment]
If you use search filters the code is run on the backend. Thus the messages will not even be sent to the frontend - and therefore not count towards the max results / 500 events limit - in case the filter returns false.

If you want to search the whole topic, use start offset = oldest, enable your search filter and start your search. Does that help?

**Comment by nitin1677** [comment]
how to read all messages / filtered messages in topic, if resulting no of messages are > 500, may be if couple of hundreds of thousands events in result. Limit with Max Results / 500 is blocking to review the events from the page.

**Comment by weeco** [comment]
Because the frontend resources are limited in browsers like Chrome it wouldn't be safe to send all messages to the frontend. That's why we limit the number of messages to 500. Does that make sense?

**Comment by victorgawk** [comment]
@nitin1677 you can follow my commit where I change size to 10.000 [here](https://github.com/victorgawk/kowl/commit/71ac6c369c76469aaac1307496f57575bbdbd481).

You probably will need also increase the timeout to list messages too since it has a default to only 45 seconds (checkout [this] (https://github.com/victorgawk/kowl/commit/89fb8fa716898b98b51ca1b2e152f355ab86e9df) another commit).

**Comment by nitin1677** [comment]
sure, let me try that.
