### ISSUE TITLE
Feature request: remember column sorting

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#426]
The default sort is set on the Offset column. Which is not always good, as messages are not evenly distributed across partitions. And in order to have a list from newest to oldest, you need to sort by Timestamp. But the setting of this sort is not remembered and you have to repeat it when entering the topic again.

My proposition is to remember column sorting or set timestamp as default sort column
or even both solutions.

**Comment by ErykCh** [comment]
![image](https://user-images.githubusercontent.com/95491982/183840476-08e32b15-3940-4fa9-ae42-ba83882596f1.png)

**Comment by weeco** [comment]
@rikimaru0345 As far as I remember we tried to store this setting per individual topic in the browser session right?

**Comment by ErykCh** [comment]
Hi, maybe this is not a big problem to add this feature and it would be very helpfull. I think i'm not the only one when looking at the table I would like to see the items sorted by default in the order they appear on the Kafka.

**Comment by weeco** [comment]
@ErykCh Since we consume messages cross partitions, there's no such order as "they appear on Kafka". The timestamp can also be set by the user to an arbitrary value. The only "right" order would be to sort by index within each partition. In fact if we consume cross partitions we have a strategy to get a few message from each partition and not try to consume the latest messages by timestamp across all partitions (users have different preferences when it comes to this).

We can save the order settings (in case we don't already do so) by topic. Would that help you?

**Comment by ErykCh** [comment]
> We can save the order settings (in case we don't already do so) by topic. 

I checked again on version 2.3.1 and it doesn't remember the sort settings.

> Would that help you?

Yes, I would be grateful.

**Comment by ErykCh** [comment]
And maybe set Timestamp as default sorting column.

**Comment by jvorcak** [comment]
This PR should fix this issue once it's merged https://github.com/redpanda-data/console/pull/1029

**Comment by twmb** [comment]
Going out with 2.4.1 today
