### ISSUE TITLE
Max Results is applied before filtering and shows fewer records than are available

### ISSUE THREAD

**Issue by oskapt** [redpanda-data/console#428]
To reproduce:

Assuming you have matching records that are > 50 records ago, which is likely if you're using owlshop:

1. Set "Max Results" to 50
2. Add a filter that would grab a small number of records, like `value.companyName != null`
3. If any results are > 50 records ago, they're not displayed
4. Set "Max Results" to 200
5. More records are displayed

I would expect that "Max Results" would be post-filter, especially since the filters are server-side. I want to see the last X results that the filter matches, not the filter matches of the last X records.

![image](https://user-images.githubusercontent.com/171292/184444519-67a092a7-0bba-4ccb-8901-9a4fc2446067.png)

![image](https://user-images.githubusercontent.com/171292/184444553-634b63e4-37e5-4a7b-b06b-a5364f237a05.png)

**Comment by weeco** [comment]
@oskapt , max results is in fact applied after the filter. The reason why you are seeing less number of records than expected is that you use "Newest-200" as start offset. And this is used before the push filters are evaluated.

If you use Start Offset = Oldest it will search all records in your topic. If you have a hunch where you messages might be in the topic (e.g. after a certain date) you could use this timestamp as a start offset.

**Comment by oskapt** [comment]
The behavior is still strange. If I have "200" in "Max Results" and then change it to "50," it changes "Start Offset" to "Newest-50." If I change it back to "200" then it changes "Start Offset" to "Newest-200." If I change it to "Oldest," then I can select any value for Max Results. It doesn't appear that I can say "Search the last 500 records and show me no more than 10 records that match my filter." As soon as I change "Max Results" to 10, it changes the Offset value.

**Comment by weeco** [comment]
> If I have "200" in "Max Results" and then change it to "50," it changes "Start Offset" to "Newest-50."

This is by design. Basically in total it makes sense to keep the label above the field to "Start offset" because of all the other options and because we can generally only consume forward in Kafka. However we wanted to offer the option to inspect the most recent messages as easy as possible. So the start offset is therefore dependent on the number of desired results, which is why these two fields have a relationship between each other.

>  It doesn't appear that I can say "Search the last 500 records and show me no more than 10 records that match my filter." As soon as I change "Max Results" to 10, it changes the Offset value.

Right. That's also by design. Reason is that there's no such easy thing like "last 500 records", because records are split across multiple partitions within a topic. So what would it last 500 records mean to you? We had to be opinionated there and the max results always limits the end result, it's possible that you end up with less records than that.


Does that make sense? I know it's not super straightforward, but considering all the possible search options it's not easy to come up with something more intuitive that works for everyone.
