### ISSUE TITLE
Show patch version for brokers

### ISSUE THREAD

**Issue by alonpr** [redpanda-data/console#432]
Currently only major.minor version is listed on the brokers page as kafka version, I believe it makes sense to include the patch version as well and not truncate it. For example, in 2.8.1 cluster it shows the version as v2.8

**Comment by weeco** [comment]
Hey @alonpr ,
the reason is that the Kafka API does not transmit the kafka version. Instead we guess the version based on the expected API versions for each kafka versions. We compare the API versions response from the cluster against what is expected for each Apache kafka version. If there's an exact match we guess this.

For Redpanda there is an additional API (the Redpanda Admin API), and in that case we can indeed report the exact version.
