### ISSUE TITLE
JSON Syntax Highlighting should not capitalise `null` in JSON

### ISSUE THREAD

**Issue by JFlath** [redpanda-data/console#495]
When viewing messages in the console, we stylise `null` properties in JSON as `NULL`. This makes it invalid JSON, as the `null` keyword is required to be lowercase.

Notably, this is only in the expanded viewer - the line in the table shows it without highlighting and therefore correctly lowercase.

<img width="1445" alt="Screenshot 2022-10-19 at 17 51 40" src="https://user-images.githubusercontent.com/6731951/196755865-4141b9c2-a996-4d25-adb5-c585a4da881a.png">

**Comment by weeco** [comment]
This is by design. You can copy the value by using the message's action menu -> Copy value, where it should be the original null.

**Comment by JFlath** [comment]
@weeco Appreciate that there's a proper way to copy the data, but what's the design reason for capitalising, rather than (e.g.) colouring and leaving lower case? We're explicitly making the representation of the JSON invalid, even if only by eye.

To give an example of why this may be important, while troubleshooting an issue, we noticed a value was `NULL`, not `null`, and went down a rabbit hole of investigating if anything in the stack may have sent a message with invalid JSON which might therefore not be accepted by consumers, before realising it was only in the UI.

**Comment by weeco** [comment]
We use a react JSON viewer as a dependency. The purpose of the JSON viewer is to provide this kind of visual guidance, rather than looking at RAW values. There's a bunch of other stuff that is injected there such as the number of array items, array element index etc.

If the RAW json is of interest, one can copy the value. We use https://github.com/TexteaInc/json-viewer where this doesn't seem to be configurable

**Comment by JFlath** [comment]
I see, thanks so much for the background :)
