### ISSUE TITLE
Consumer Group Offset Management

### ISSUE THREAD

**Issue by michaelandrepearce** [redpanda-data/console#566]
As with other tools like Lenses , Kpow etc, they offer ability to adjust the consumer group offsets, when consumers are detached.

This is useful in being able to rewind consumers if needed or skip them past bad records they maybe stuck on.

e.g.

![image](https://user-images.githubusercontent.com/1387822/205172324-46cacb88-5be8-41f0-b917-f9de042da2c6.png)

As well it would be useful to be able to delete a consumer group and create with a set initial offset.

**Comment by weeco** [comment]
Hey @michaelandrepearce ,
everything you mentioned + copying offsets from existing consumer groups is already supported. You can just browse to a consumer group and click "Edit group" or "Delete group". The consumer group has to be inactive otherwise the active group members would just immediately overwrite the changes by committing an offset again. Console enforces that behaviour by disabling the button + API as long as a group is still active.

The only missing feature would be creating an empty consumer group with offsets of your choice. Could you describe your usecase why this is beneficial to you and potentially other users?

**Comment by michaelandrepearce** [comment]
Which version is this in? I took only the other week a version and I couldn't see these items you mention.

**Comment by weeco** [comment]
@michaelandrepearce I'm unsure when exactly it has been added, but it has been part of Console / Kowl for more than a year. Please let me know if you can't find the options.
