### ISSUE TITLE
Enable SSL on the Front end.

### ISSUE THREAD

**Issue by archeious** [redpanda-data/console#580]
I might have missed it in the configuration but is it possible to enable SSL on the front end on the console?

**Comment by weeco** [comment]
Hello,
it's currently not possible to configure the Console backend to use provided SSL certificates. I noticed that this would be a handy option to have especially in environments where you don't want to use a reverse proxy such as NGINX which takes care of the TLS termination. 

Since you mentioned configuring the **frontend**:  If you actually refer to the frontend sending HTTPS requests - this should be the case by default as it's just sending requests to relative URLs.

**Comment by archeious** [comment]
Darn.  I have SSL for the producers and consumers of the cluster and SSL from the console into the cluster.  We have a security policy that all network end have to be encrypted.  Sounds like I need a reverse proxy on the same VM as the console.
