### ISSUE TITLE
Feature Request: Configuration for Json-Viewer Collapse level

### ISSUE THREAD

**Issue by brycefisher** [redpanda-data/console#607]
## Problem

We have many kafka messages which decode as deeply nested json objects that we want to inspect in Redpanda Console, but the current hardcoded [collapse level of 2](https://github.com/redpanda-data/console/blob/2fbffa303c2ec92de39673e0a8e0a358f90a7c43/frontend/src/components/misc/KowlJsonView.tsx#L101) adds some toil to discovering what information is present in such a message:
<img width="695" alt="Screenshot 2023-01-30 at 2 34 42 PM" src="https://user-images.githubusercontent.com/220106/215611517-04ef2e9c-9d83-4889-8909-2015746d5e42.png">

## Proposed Solution

Instead of hardcoding the `collapsed` prop to 2, I'd love to add a new Config field [somewhere](https://github.com/redpanda-data/console/blob/master/backend/pkg/config/console.go#L19) field that controls the depth of JSON objects that are collapsed, keeping the default setting at 2 to match existing behavior.

**Comment by weeco** [comment]
Hey @brycefisher ,
thanks for filing this issue - that makes sense to me.

I think we could add a configuration option in the frontend so that each user can configure this as desired. We already have some config options for the JSON viewer, so just adding an additional configuration there should be easy

![screenshot 2023-02-05 at 08 03 37@2x](https://user-images.githubusercontent.com/23424570/216806248-4425977e-6509-4dfc-88e1-bb6c13ed9e0e.png)

Do you want to submit a pull request for this?

**Comment by brycefisher** [comment]
I love that! Any chance we could the default in server side configs for users who didn't set a default?

**Comment by brycefisher** [comment]
...and yes! I'll work on a PR for this. Seems straightforward, except maybe wiring up server side defaults.

**Comment by brycefisher** [comment]
This is now in the unstable docker images of console. Woot! Thanks all

**Comment by ErykCh** [comment]
Where can I find these unstable versions of images?

**Comment by weeco** [comment]
@ErykCh here: https://hub.docker.com/r/redpandadata/console-unstable/tags
