### ISSUE TITLE
Not showing all messages

### ISSUE THREAD

**Issue by ebcFlagman** [redpanda-data/console#633]
we have the problem that we receive inconsistent messages in the topic view. Every time I hit the refresh button I got different messages. We had a Kafka cluster of 3 brokers.

![image](https://user-images.githubusercontent.com/1026771/220860399-bd410e91-eef7-49e8-885d-fac14c2966c2.png)

![image](https://user-images.githubusercontent.com/1026771/220860444-b254e860-7dba-4d45-ae26-1f9384a55d15.png)

Any idea why this happen?

**Comment by weeco** [comment]
Hey @ebcFlagman ,
we have to make a lot of assumptions on how we want to consume and render these messages to the user when we consume cross partitions.

If you think about implementing this you have to make a decision like:
- Would it be okay if we send messages from only one partition for across all partitions or should we try to balance the number of records across partitions?
- Because we can only consume forwards and not backwards - how do we handle gaps due to compaction? Do we have to consume further previous messages until we have our desired number of records for that specific partition or are we okay getting messages from other partitions in that case?
- What do we do if one partition doesn't yield enough messages but another partition has enough messages because the number of kafka records across partitions is skewed. We had the assumption that the user always wants to see 50 messages in the case of newest-50 if max results is set to 50
- Should we order this chronologically, grouped by partition, can we just send them to the frontend as they are consumed to reduce latency, by offset ...

All these kind of questions - along with all it's other features such as filtering messages it's possibly one of the most complex parts of Console. To answer your question: Some variety is expected depending on your partition count, message count in each partition and configured max results. 

Newest-50 was supposed to give the user a good idea of what recent data in your topic would look like. If you consume the newest messages for a specific partition you should get more predictable results. Does that help?

**Comment by ebcFlagman** [comment]
thx @weeco for your explanations, it's now clear for me, that we cannot use redpanda console for this case.
