### ISSUE TITLE
We can't see the messages

### ISSUE THREAD

**Issue by mhmtszr** [redpanda-data/console#691]
https://github.com/redpanda-data/console/issues/553 We are still facing the same issue, I tried giving "SERVER_ALLOWEDORIGINS" env variable I also tried to update my config as
```
server:
  allowedOrigins: ["https://my-service.com"]
```
I also tried to downgrade to v2.1.1 still same problem.
"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"
Could you please help us?

**Comment by weeco** [comment]
Issues related to websockets are usually caused by reverse proxies or loadbalancers in front of Console that don't support websockets. You only need to set the allowed origins in very specific scenarios - so I doubt this is the cause. If it is, you'd also see CORS issues in your Chrome browser (even though they are a little hidden for Websocket requests). 

Thus, based on the limited available information I'd suspect either the reverse proxy or loadbalancer in front of Console. Any insights on that?

**Comment by mhmtszr** [comment]
I think you are right, most probably there is a firewall rule in our reverse proxy, It does not accept websocket requests I will try to focus there thanks.
