### ISSUE TITLE
OAUTHBEARER sasl mechanism

### ISSUE THREAD

**Issue by vfolgosa** [redpanda-data/console#699]
Hi guys, I have a question, to use the OAUTHBEARER sasl mechanism, do I have to generate the token outside the application and put it in the config kafka.sasl.oauth.token?

So if the token expires do I need to update the config and restart the console?

**Comment by weeco** [comment]
Hey @vfolgosa ,
based on our Slack thread I assume you want to use short-lived tokens which need to be refreshed periodically. Currently this is not supported (neither in Console, nor the Kafka client we use). I'd need to look in more detail how this should work and possibly this should be implemented upstream in the franz-go client rather than Console. I'll leave this issue in Console open anyways, but you could create a separate one in https://github.com/twmb/franz-go too.

**Comment by cthtrifork** [comment]
FYI

https://github.com/twmb/franz-go/issues/482

**Comment by cthtrifork** [comment]
> The oauth package itself provides an `Oauth` function,
> 
> 
> 
> ```
> 
> func Oauth(authFn func(context.Context) (Auth, error)) sasl.Mechanism {
> 
> ```
> 
> 
> 
> You can use this to create a new Auth with a new short lived token:
> 
> 
> 
> ```
> 
> kgo.SASL(oauth.Oauth(func(ctx context.Context) (oauth.Auth, error) {
> 
>     shortToken, err := aquireToken(ctx)
> 
>     return oauth.Auth{Token: shortToken}, err
> 
> }))
> 
> ```
> 
> The `Auth.AsMechanism` function is only provided if you don't intend to change the token
> 
> 
> 
> note the aws_msk_iam example, which is similar in concept:
> 
> https://github.com/twmb/franz-go/blob/a61b2fa4407091ae3679cea5868dbd128f3a995b/examples/sasl/aws_msk_iam/main.go#L41

**Comment by cthtrifork** [comment]
This should be closed 😄
