### ISSUE TITLE
[Bug] ACLs in the UI don't seem to be responsive

### ISSUE THREAD

**Issue by asachs01** [redpanda-data/console#749]
## Expected behavior

When using the console, I expect to see ACLs be responsive to the screen size. 

## Current behavior

Currently, ACLs don't seem to be responsive to the screen size and the ACL items don't all cleanly fit inside the respective section's flex box

![CleanShot 2023-06-28 at 15 37 27](https://github.com/redpanda-data/console/assets/898627/207ad847-4767-40b7-a123-f5615dca6b1f)

## System information

Browser info: https://www.whatsmybrowser.org/b/4X3O4
Redpanda console version: v23.1
Deployment method: Docker

**Comment by weeco** [comment]
Hey @asachs01 ,
thanks for filing the issue and providing this gif. We decided to not spend additional working cycles on a responsive design because the vast majority of people using Console use it from their desktop / a reasonably sized device. Thus, almost the entire UI is not responsive and expects a certain min browser width.

We have some plans to re-work this specific dialogue anyways though. For above reason I'm closing this issue, but any additional insight why a responsive design may be important to you is appreciated and will be considered.
